package com.example.demo.entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.user_id
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.user_name
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.user_password
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.salt
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.user_phone_number
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    private Integer userPhoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.user_email_number
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    private String userEmailNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.create_time
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.create_user
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.update_time
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.update_user
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.user_id
     *
     * @return the value of tbl_user.user_id
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.user_id
     *
     * @param userId the value for tbl_user.user_id
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.user_name
     *
     * @return the value of tbl_user.user_name
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.user_name
     *
     * @param userName the value for tbl_user.user_name
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.user_password
     *
     * @return the value of tbl_user.user_password
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.user_password
     *
     * @param userPassword the value for tbl_user.user_password
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.salt
     *
     * @return the value of tbl_user.salt
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.salt
     *
     * @param salt the value for tbl_user.salt
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.user_phone_number
     *
     * @return the value of tbl_user.user_phone_number
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    public Integer getUserPhoneNumber() {
        return userPhoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.user_phone_number
     *
     * @param userPhoneNumber the value for tbl_user.user_phone_number
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    public void setUserPhoneNumber(Integer userPhoneNumber) {
        this.userPhoneNumber = userPhoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.user_email_number
     *
     * @return the value of tbl_user.user_email_number
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    public String getUserEmailNumber() {
        return userEmailNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.user_email_number
     *
     * @param userEmailNumber the value for tbl_user.user_email_number
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    public void setUserEmailNumber(String userEmailNumber) {
        this.userEmailNumber = userEmailNumber == null ? null : userEmailNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.create_time
     *
     * @return the value of tbl_user.create_time
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.create_time
     *
     * @param createTime the value for tbl_user.create_time
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.create_user
     *
     * @return the value of tbl_user.create_user
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.create_user
     *
     * @param createUser the value for tbl_user.create_user
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.update_time
     *
     * @return the value of tbl_user.update_time
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.update_time
     *
     * @param updateTime the value for tbl_user.update_time
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.update_user
     *
     * @return the value of tbl_user.update_user
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.update_user
     *
     * @param updateUser the value for tbl_user.update_user
     *
     * @mbg.generated Thu Jun 27 15:10:32 CST 2024
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}
